### ISSUE TITLE
switch CI to Github Actions

### ISSUE THREAD

**Issue by cderv** [RLesur/crrri#96]
Would be a good exercice and it will allow also windows build.

**Comment by RLesur** [comment]
Good idea! 

I've tested whether Chrome was available in GHA 6 months ago. It was installed on linux and Windows. For macOS I had to install it with:

```yaml
jobs:
    steps:
      - name: Install Chrome (only on macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew cask install google-chrome
 ```
